### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by gkeller2** [digs-uwo/dcsim#3]
@mtighe : we need to add some documentation here. A README file to start with, I guess. This file could have some references to papers that we wrote using the simulator. Also, some description of the simulator would be good. This is not a priority, but perhaps making a report with your thesis chapter on DCSim could work.

Thoughts?

**Comment by mtighe** [comment]
Definitely. A basic readme file to get people up and running, and a couple of wiki pages with the content from my thesis chapter. Also, we should put licensing information somewhere (under a "do whatever you want with it, and it would be nice if you reference our papers" license)

**Comment by gkeller2** [comment]
So, README file with some instructions to use the simulator, and references to papers. Wiki pages with thesis chapter.

As for license, I've already added a file for that. Chose GNU, that is what we had originally discussed several years ago. Sounds good?

**Comment by mtighe** [comment]
Yeah, that's fine with me. References to papers should be in the wiki as well.

**Comment by mtighe** [comment]
In fact, if we are upload all of our research work, we should have a short section listing the papers and which files were used in each... although, for older work, that's not really possible due to substantial simulator modifications, but we can point people to the current versions of those algorithms even if the results will vary slightly from the papers.

**Comment by gkeller2** [comment]
Sounds good.

Hadn't you written some basic instructions to use DCSim for the people in Ottawa? Could we use that as a basis for the README file?

**Comment by gkeller2** [comment]
Any interest in these features of GitHub?
- Making Code Citable -- https://guides.github.com/activities/citable-code/
- GitHub Pages -- https://guides.github.com/features/pages/

A GitHub Page would just serve as a front page for DCSim, nothing more.

**Comment by mtighe** [comment]
I'm not sure if I wrote instructions for them... I wrote a document describing how it works, but that was merged into my thesis chapter. I'm not sure about using github pages, I think for starters just using the built-in wiki would be good enough, and easy. Not sure about the citable code thing... what is the purpose of it exactly?

**Comment by gkeller2** [comment]
Wiki works.

The purpose of citable code is, according to my shallow understanding of it, something equivalent to tagging a certain version of the software, so that when you write a paper you can indicate the version of the software that you used in your experiments. It would have been useful in our work several years ago. Now, it could only serve future users (if there are any  =) ).

**Comment by mtighe** [comment]
Ah, I see. Yeah, would have been useful in the past, not so much now.

**Comment by gkeller2** [comment]
Added a list of publications to the wiki of the _dcsim-projects_ repository. We could add the same list here.

**Comment by mtighe** [comment]
Can you add the list to the wiki-in-progress? There is already a placeholder "table to contents" item on the home page, you can add a new page and then we can link to it from there.

**Comment by mtighe** [comment]
Wiki documentation has been added. Just need a basic README to get people up-and-running, and we're set.

**Comment by mtighe** [comment]
Added readme file.
