### ISSUE TITLE
Upload projects' code

### ISSUE THREAD

**Issue by gkeller2** [digs-uwo/dcsim#5]
Mike, as we discussed before, we should upload the code from our past projects. Personally, I'd keep them in a different repository from DCSim. I'd suggest renaming the repository from _digs-projects_ to _dcsim-projects_.  What do you think?

If we go ahead, is all your code merged into the master branch of _digs-projects_? My branch _dependencies_ hasn't been merged yet, but I'm going to wait until I'm done with the IM 2015 paper before uploading the code.

**Comment by mtighe** [comment]
I'm not sure about my code... I will take a look at it shortly. As for _where_ to put our projects... I see the argument that it should be in a separate repository, but at the same time, it might be more convenient for everything to be in the same place, so if someone gets the simulator, they will have lots of examples and algorithms to try out with it. Furthermore, if people want to contribute more experiments and algorithms, everything can just be included with the DCSim code.

**Comment by mtighe** [comment]
Ok, it looks like all of my code is already up-to-date in the digs projects repo. I had some other work on my local machine, but nothing usable (failed research ideas). What do you think, do you want to start a new repo or just pull the projects package into this one?

**Comment by gkeller2** [comment]
I see your point, but I still think that simulator and projects should be kept apart, so as to keep the simulator itself independent of any project that actually makes use of it. In that way, if somebody wants to use the simulator and add features, they don't have in the repository a lot of other stuff that doesn't need to be there.

**Comment by mtighe** [comment]
Ok, let's go with a separate repo then.

**Comment by mtighe** [comment]
We might want to call it DCSim-Projects instead of DIGS-Projects, to reflect that it's all projects using dcsim. Do you want to set it up, or shall I?

**Comment by gkeller2** [comment]
Yeah... like I said in the opening message: _I'd suggest renaming the repository from digs-projects to dcsim-projects._ =P

I'll do it. Maybe you can start with the wiki?

**Comment by mtighe** [comment]
Ha, somehow I missed that. Ok, I'm on the wiki.

**Comment by gkeller2** [comment]
Done. Created repository _dcsim-projects_.
